# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Escoria Framework
email: contact@escoria-framework.org
description: >- # this means to ignore newlines until "baseurl:"
  A complete, free and open-source framework to help you create point and click adventure games with
  Godot Engine.
show_downloads: true

docs_url: https://docs.escoria-framework.org

github:
  is_project_page: true
  repository_url: https://github.com/godot-escoria/escoria-demo-game
  zip_url: https://github.com/godot-escoria/escoria-demo-game/archive/refs/heads/main.zip

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://escoria-framework.org" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: godot-escoria

# Build settings
markdown: kramdown
#theme: minima
#remote_theme: pages-themes/cayman@v0.2.0
theme: jekyll-theme-cayman

#remote_theme: pages-themes/architect@v0.2.0


plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
